openapi: 3.0.0
info:
  title: social-api
  version: '1.0'
  contact:
    name: Balint Jeszenszky
  description: Social service
servers:
  - url: 'http://localhost/api/social'
    description: docker
  - url: 'http://localhost:8081/api/social'
    description: local
paths:
  '/post/{postId}':
    parameters:
      - schema:
          type: integer
        name: postId
        in: path
        required: true
    put:
      summary: ''
      operationId: put-post-postId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostDto'
        '400':
          description: Bad Request
        '403':
          description: Forbidden
      description: edit post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPostDto'
      tags:
        - post
    delete:
      summary: ''
      operationId: delete-post-postId
      responses:
        '204':
          description: No Content
        '403':
          description: Forbidden
      description: delete post
      tags:
        - post
  /post:
    post:
      summary: ''
      operationId: post-post
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostDto'
        '400':
          description: Bad Request
      description: Create new post
      tags:
        - post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPostDto'
  /post/all:
    get:
      summary: Your GET endpoint
      tags:
        - post
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PostDto'
      operationId: get-post-all
      description: Get all friends posts
  '/post/all/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - post
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PostDto'
      operationId: get-post-all-userId
      description: Get posts from user
  '/friend/{id}':
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
    post:
      summary: ''
      operationId: post-friend-id
      responses:
        '201':
          description: Created
        '404':
          description: Not Found
      description: send or accept friend request
      tags:
        - friends
    delete:
      summary: ''
      operationId: delete-friend-id
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
      description: delete friend or friend request
      tags:
        - friends
  '/friend/list/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - friends
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDetailsDto'
      operationId: get-friend-list-userId
      description: list friends of a user
  /friend/requests:
    get:
      summary: Your GET endpoint
      tags:
        - friends
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDetailsDto'
      operationId: get-friend-requests
      description: List of pending requests
  '/media/{id}':
    put:
      summary: ''
      operationId: put-media
      responses:
        '202':
          description: Accepted
        '404':
          description: Not Found
      description: Notify of status change
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MediaStatusDto'
      tags:
        - media-access
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
    get:
      summary: ''
      operationId: get-media-id
      responses:
        '200':
          description: OK
      description: Get url with key for media
      tags:
        - media-access
  '/like/{postId}':
    parameters:
      - schema:
          type: integer
        name: postId
        in: path
        required: true
    post:
      summary: ''
      operationId: post-like-postId
      responses:
        '201':
          description: Created
        '404':
          description: Not Found
      description: like a post
      tags:
        - like
    delete:
      summary: ''
      operationId: delete-like-postId
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
      description: remove like from post
      tags:
        - like
  /delete:
    parameters: []
    delete:
      summary: ''
      operationId: delete-delete-userId
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
      tags:
        - delete-social
      description: Delete everithing connected to user
components:
  schemas:
    NewPostDto:
      title: NewPostDto
      type: object
      properties:
        text:
          type: string
        media:
          type: boolean
      required:
        - text
        - media
    PostDto:
      title: PostDto
      type: object
      properties:
        id:
          type: integer
        text:
          type: string
        user:
          $ref: '#/components/schemas/UserDetailsDto'
        created:
          type: string
          format: date-time
        likes:
          type: integer
        liked:
          type: boolean
        mediaName:
          type: string
        processedMedia:
          type: boolean
      required:
        - id
        - text
        - user
        - created
        - likes
        - liked
    UserDetailsDto:
      title: UserDetailsDto
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
      required:
        - id
        - username
        - firstname
        - lastname
        - email
    MediaStatusDto:
      title: MediaStatusDto
      type: object
      properties:
        status:
          type: string
          enum:
            - PROCESSING
            - FAILED
            - AVAILABLE
        name:
          type: string
      required:
        - status
  securitySchemes: {}
tags:
  - name: post
  - name: friends
  - name: media-access
  - name: like
  - name: delete-social
